[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Archive"
pageRef = "paper-reviews"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 20

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/deep-diver/paper-reviewer/"
weight = 50

[[main]]
identifier = "twitter"
pre = "twitter"
url = "https://twitter.com/algo_diver/"
weight = 60

[[main]]
name = "2025-01-31"
pageRef = "2025-01-31"
weight = 20

[[main]]
name = "2025-02-04"
pageRef = "2025-02-04"
weight = 20

[[main]]
name = "2025-02-05"
pageRef = "2025-02-05"
weight = 20

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "NeurIPS2024"
url = "https://deep-diver.github.io/neurips2024/"
weight = 20

