[[main]]
name = "About"
pageRef = "about"
weight = 10

[[main]]
name = "Paper Reviews"
pageRef = "paper-reviews"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 20

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/deep-diver/paper-reviewer/"
weight = 50

[[main]]
identifier = "twitter"
pre = "twitter"
url = "https://twitter.com/algo_diver/"
weight = 60

[[main]]
name = "2025-01-16"
pageRef = "2025-01-16"
weight = 20

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

