colorScheme = "Congo"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "2025-03-13",]

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "img/cover.png"
showRecent = true
showRecentItems = 9
showMoreLink = true
showMoreLinkDest = "/ai-paper-reviewer/paper-reviews/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = true
showViews = true
showLikes = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showSummary = true
showComments = true
sharingLinks = [ "linkedin", "twitter", "email",]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
showTaxonomies = true

[buymeacoffee]
identifier = "chansung"
globalWidget = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]
apiKey = "AIzaSyCv6pUES05bxrampKbfhhmW3y-1pmX3XgE"
authDomain = "neurips2024-f3065.firebaseapp.com"
projectId = "neurips2024-f3065"
storageBucket = "neurips2024-f3065.firebasestorage.app"
messagingSenderId = "982475958898"
appId = "1:982475958898:web:2147e5d7753d6ac091f0eb"
measurementId = "G-YQ46HXQ9JS"

[fathomAnalytics]

[verification]
